<?php
/**
 * @file
 * Module for defining custom hooks. Good place to add custom module code.
 */

/**
 * Implements hook_menu().
 */
function d7_csbase_menu() {
  // Adds Homepage
  $items['home'] = array(
    'title' => 'Home',
    'page callback' => 'get_homepage',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  // Adds Spotify Callback page - see sites/all/themes/ewo/assets/coffee/spotify_add_to_playlist
  $items['spotify-callback'] = array(
    'title' => 'Spotify Callback',
    'page callback' => 'get_homepage',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

function get_homepage()
{
  return '';
}

/**
 * Implements hook_form_FORMID_alter().
 */
function d7_csbase_form_song_node_form_alter(&$form, &$form_state, $form_id) {
  // Add Prefix text to link fields
  $form['field_itunes_link'][LANGUAGE_NONE][0]['#field_prefix'] = 'https://geo.itunes.apple.com/us/album/';
  $form['field_multitracks_link'][LANGUAGE_NONE][0]['#field_prefix'] = 'http://www.multitracks.com/afe/esstw/?t=/';
  $form['field_praisecharts_link'][LANGUAGE_NONE][0]['#field_prefix'] = 'http://www.praisecharts.com/detail/arrangement/';
  $form['field_loopcommunity_link'][LANGUAGE_NONE][0]['#field_prefix'] = 'http://loopcommunity.com/';
}

/**
 * Implements hook_form_alter().
 */
function d7_csbase_form_alter(&$form, &$form_state, $form_id) {
  // Mailchimp forms
  if (!empty($form_state['build_info']['base_form_id'])) {
    if ($form_state['build_info']['base_form_id'] == 'mailchimp_signup_subscribe_form') {
      $form['mergevars']['EMAIL']['#attributes']['placeholder'] = t('enter email address');
      //     if (isset($form['mailchimp_lists'][$field_id]['subscribe'])) {
      //       $form['mailchimp_lists'][$field_id]['subscribe']['#default_value'] = TRUE;
      //     }
      //   }
      // }
    }
  }
}

/**
 * Menu callback; process one time login link and redirects to the user page on success.
 */
function d7_csbase_pass_reset($form, &$form_state, $uid, $timestamp, $hashed_pass, $action = NULL) {
  global $user;

  // When processing the one-time login link, we have to make sure that a user
  // isn't already logged in.
  if ($user->uid) {
    // The existing user is already logged in.
    if ($user->uid == $uid) {
      drupal_set_message(t('You are logged in as %user. <a href="!user_edit">Change your password.</a>', array('%user' => $user->name, '!user_edit' => url("user/$user->uid/edit"))));
    }
    // A different user is already logged in on the computer.
    else {
      $reset_link_account = user_load($uid);
      if (!empty($reset_link_account)) {
        drupal_set_message(t('Another user (%other_user) is already logged into the site on this computer, but you tried to use a one-time link for user %resetting_user. Please <a href="!logout">logout</a> and try using the link again.',
          array('%other_user' => $user->name, '%resetting_user' => $reset_link_account->name, '!logout' => url('user/logout'))));
      } else {
        // Invalid one-time link specifies an unknown user.
        drupal_set_message(t('The one-time login link you clicked is invalid.'));
      }
    }
    drupal_goto();
  }
  else {
    // Time out, in seconds, until login URL expires. Defaults to 24 hours =
    // 86400 seconds.
    $timeout = variable_get('user_password_reset_timeout', 86400);
    $current = REQUEST_TIME;
    // Some redundant checks for extra security ?
    $users = user_load_multiple(array($uid), array('status' => '1'));
    if ($timestamp <= $current && $account = reset($users)) {
      // No time out for first time login.
      if ($account->login && $current - $timestamp > $timeout) {
        drupal_set_message(t('You have tried to use a one-time login link that has expired. Please request a new one using the form below.'));
        drupal_goto('user/password');
      }
      elseif ($account->uid && $timestamp >= $account->login && $timestamp <= $current && $hashed_pass == user_pass_rehash($account->pass, $timestamp, $account->login, $account->uid)) {
        // First stage is a confirmation form, then login
        if ($action == 'login') {
          // Set the new user.
          $user = $account;
          // user_login_finalize() also updates the login timestamp of the
          // user, which invalidates further use of the one-time login link.
          user_login_finalize();
          watchdog('user', 'User %name used one-time login link at time %timestamp.', array('%name' => $account->name, '%timestamp' => $timestamp));
          drupal_set_message(t('You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password.'));
          // Let the user's password be changed without the current password check.
          $token = drupal_random_key();
          $_SESSION['pass_reset_' . $user->uid] = $token;
          drupal_goto('user/' . $user->uid . '/edit', array('query' => array('pass-reset-token' => $token)));
        }
        else {
          $form['message'] = array('#markup' => t('<p>This is a one-time login for %user_mail and will expire on %expiration_date.</p><p>Click on this button to log in to the site and change your password.</p>', array('%user_mail' => $account->mail, '%expiration_date' => format_date($timestamp + $timeout))));
          $form['help'] = array('#markup' => '<p>' . t('This login can be used only once.') . '</p>');
          $form['actions'] = array('#type' => 'actions');
          $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Log in'));
          $form['#action'] = url("user/reset/$uid/$timestamp/$hashed_pass/login");
          return $form;
        }
      }
      else {
        drupal_set_message(t('You have tried to use a one-time login link that has either been used or is no longer valid. Please request a new one using the form below.'));
        drupal_goto('user/password');
      }
    }
    else {
      // Deny access, no more clues.
      // Everything will be in the watchdog's URL for the administrator to check.
      drupal_access_denied();
      drupal_exit();
    }
  }
}
